# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - run:
          name: Test
          command: python tests.py
      - run:
          name: Congratulations!
          command: echo $SUCCESS_MESSAGE
          shell: /bin/bash -eo pipefail -x
      - run:
          name: And now...
          command: echo $INSTRUCTIONS
          shell: /bin/bash -eo pipefail -x
      - run:
          name: It at first you don't succeed...
          command: echo ... dust yourself off, and try again
          shell: /bin/bash -eo pipefail -x
          when: on_fail